version: '3.9'
services:
  dev-db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret
      POSTGRES_DB: nestjs
